# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    environment: staging
    env:
      REACT_APP_DEPLOY_TARGET: "STAGING"

    strategy:
      matrix:
        node-version: [16.15]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: CI=false yarn workspace dapp build --if-present
    - run: yarn workspace services build --if-present
    - run: cp -r packages/dapp/dist/build/ packages/services/dist/
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/465342684515/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: 'github-staging@kernel-services-staging.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - run: yarn workspace services deploy:staging
      
